#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "${ROOT_DIR}/tests/_search.sh"

assert_contains() {
  local path="$1"
  local pattern="$2"
  if ! search_contains "${pattern}" "${ROOT_DIR}/${path}"; then
    echo "[FAIL] '${pattern}' not found in ${path}"
    exit 1
  fi
  echo "[PASS] '${pattern}' found in ${path}"
}

assert_not_contains() {
  local path="$1"
  local pattern="$2"
  if search_contains "${pattern}" "${ROOT_DIR}/${path}"; then
    echo "[FAIL] '${pattern}' should not exist in ${path}"
    exit 1
  fi
  echo "[PASS] '${pattern}' not found in ${path}"
}

(cd "${ROOT_DIR}" && npm run build:pages >/dev/null)

aassert_path="fe/public/dunsmile/daily-fortune/index.html"
assert_contains "${aassert_path}" "generated by scripts/build-static-pages.js"
assert_contains "${aassert_path}" "id=\"step1\""
assert_contains "${aassert_path}" "오늘의 운세 풀이"
assert_contains "${aassert_path}" "/dunsmile/js/daily-fortune.js"
assert_not_contains "${aassert_path}" "/dunsmile/js/service-shell.js"
assert_contains "${aassert_path}" "data-related-carousel-service=\"daily-fortune\""
assert_contains "${aassert_path}" "dp-service-frame"

bassert_path="fe/public/dunsmile/rich-face/index.html"
assert_contains "${bassert_path}" "id=\"step1\""
assert_contains "${bassert_path}" "AI 관상 테스트"
assert_contains "${bassert_path}" "/dunsmile/js/face-test.js"
assert_not_contains "${bassert_path}" "/dunsmile/js/service-shell.js"
assert_contains "${bassert_path}" "data-related-carousel-service=\"rich-face\""

cassert_path="fe/public/dunsmile/balance-game/index.html"
assert_contains "${cassert_path}" "svc-shell svc-theme-balance"
assert_contains "${cassert_path}" "/dunsmile/js/balance-game.js"
assert_not_contains "${cassert_path}" "/dunsmile/js/service-shell.js"
assert_contains "${cassert_path}" "data-related-carousel-service=\"balance-game\""

dassert_path="fe/public/dunsmile/name-compatibility/index.html"
assert_contains "${dassert_path}" "svc-shell svc-theme-compat"
assert_contains "${dassert_path}" "/dunsmile/js/name-compatibility.js"
assert_not_contains "${dassert_path}" "/dunsmile/js/service-shell.js"
assert_contains "${dassert_path}" "data-related-carousel-service=\"name-compatibility\""

eassert_path="fe/public/dunsmile/hoxy-number/index.html"
assert_contains "${eassert_path}" "무료 로또 번호 생성기"
assert_contains "${eassert_path}" "../js/app.js"
assert_contains "${eassert_path}" "data-related-carousel-service=\"hoxy-number\""

fassert_path="fe/public/dunsmile/tarot-reading/index.html"
assert_contains "${fassert_path}" "ONE DAY MY CARD"
assert_contains "${fassert_path}" "../js/tarot-reading.js"
assert_contains "${fassert_path}" "data-related-carousel-service=\"tarot-reading\""

gassert_path="fe/public/dunsmile/market-sentiment/index.html"
assert_contains "${gassert_path}" "시장 감성 레이더"
assert_contains "${gassert_path}" "/dunsmile/js/market-sentiment.js"
assert_contains "${gassert_path}" "data-related-carousel-service=\"market-sentiment\""

hassert_path="fe/public/dunsmile/wealth-dna-test/index.html"
assert_contains "${hassert_path}" "부자 DNA 테스트"
assert_contains "${hassert_path}" "/dunsmile/js/wealth-dna-test.js"
assert_contains "${hassert_path}" "data-related-carousel-service=\"wealth-dna-test\""

node -e "const fs=require('fs');const root='${ROOT_DIR}';const checks=[['fe/public/dunsmile/daily-fortune/index.html',3],['fe/public/dunsmile/rich-face/index.html',2],['fe/public/dunsmile/hoxy-number/index.html',1],['fe/public/dunsmile/tarot-reading/index.html',3],['fe/public/dunsmile/balance-game/index.html',1],['fe/public/dunsmile/name-compatibility/index.html',1],['fe/public/dunsmile/market-sentiment/index.html',1],['fe/public/dunsmile/wealth-dna-test/index.html',1]]; for (const [p,sections] of checks){const s=fs.readFileSync(root+'/'+p,'utf8');const sectionCount=(s.match(/data-related-carousel-service=\"[^\"]+\"/g)||[]).length;const cardCount=(s.match(/class=\"svc-related-card /g)||[]).length;const min=sections*6;if(sectionCount<sections||cardCount<min){console.error('[FAIL] carousel card count too low in '+p+' expected sections='+sections+', cards>='+min+', got sections='+sectionCount+', cards='+cardCount); process.exit(1);} } console.log('[PASS] carousel card counts >= 6 per section');" \
  || exit 1

echo "[PASS] static page generation checks complete"
