#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const CONFIG_PATH = path.join(ROOT, 'fe/src/ssg/static-pages.json');
const GENERATED_BANNER = '<!-- generated by scripts/build-static-pages.js; do not edit directly -->';
const CANONICAL_BASE = 'https://dopamine-factory.pages.dev';

function fail(msg) {
  console.error(`[test-build] ${msg}`);
  process.exit(1);
}

function pass(msg) {
  console.log(`[PASS] ${msg}`);
}

if (!fs.existsSync(CONFIG_PATH)) fail(`Missing config: ${CONFIG_PATH}`);

const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
const pages = Array.isArray(config.pages) ? config.pages : [];
if (pages.length === 0) fail('No pages in fe/src/ssg/static-pages.json');

const checks = [
  { key: 'doctype', re: /<!DOCTYPE html>/i },
  { key: 'lang', re: /<html[^>]*\slang=["'][^"']+["'][^>]*>/i },
  { key: 'head', re: /<head>[\s\S]*<\/head>/i },
  { key: 'body', re: /<body[^>]*>[\s\S]*<\/body>/i },
  { key: 'title', re: /<title>[^<]+<\/title>/i },
  { key: 'description', re: /<meta\s+name=["']description["']\s+content=["'][^"']+["']/i },
  { key: 'canonical', re: /<link\s+rel=["']canonical["']\s+href=["'][^"']+["']/i },
  { key: 'charset', re: /<meta\s+charset=["']?utf-8["']?/i },
  { key: 'viewport', re: /<meta\s+name=["']viewport["']\s+content=["'][^"']+["']/i },
];

function expectedCanonicalFromOutput(outputPath) {
  const normalized = String(outputPath || '').replace(/^fe\/public/, '').replace(/index\.html$/, '');
  return `${CANONICAL_BASE}${normalized}`;
}

function getMetaContent(html, attr, key) {
  const re = new RegExp(`<meta\\s+[^>]*${attr}=["']${key}["'][^>]*content=["']([^"']+)["'][^>]*>`, 'i');
  const matched = html.match(re);
  return matched ? matched[1] : '';
}

function getCanonicalHref(html) {
  const matched = html.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']+)["']/i);
  return matched ? matched[1] : '';
}

let inspected = 0;
for (const page of pages) {
  const output = page.output;
  const target = path.join(ROOT, output);
  if (!fs.existsSync(target)) fail(`Missing built output: ${output}`);

  const html = fs.readFileSync(target, 'utf8');
  if (!html.startsWith(GENERATED_BANNER)) {
    fail(`${output} missing generated banner`);
  }
  if (/\{\{BODY\}\}/.test(html)) {
    fail(`${output} still contains {{BODY}} placeholder`);
  }

  for (const check of checks) {
    if (!check.re.test(html)) {
      fail(`${output} missing ${check.key}`);
    }
  }

  const expectedCanonical = expectedCanonicalFromOutput(output);
  const actualCanonical = getCanonicalHref(html);
  if (actualCanonical !== expectedCanonical) {
    fail(`${output} canonical mismatch: expected '${expectedCanonical}', got '${actualCanonical || '(missing)'}'`);
  }

  const ogTitle = getMetaContent(html, 'property', 'og:title');
  const ogDescription = getMetaContent(html, 'property', 'og:description');
  const ogUrl = getMetaContent(html, 'property', 'og:url');
  const ogImage = getMetaContent(html, 'property', 'og:image');
  if (!ogTitle || !ogDescription || !ogUrl || !ogImage) {
    fail(`${output} missing required OG tags (title/description/url/image)`);
  }
  if (ogUrl !== actualCanonical) {
    fail(`${output} og:url mismatch with canonical`);
  }

  const twCard = getMetaContent(html, 'name', 'twitter:card');
  const twTitle = getMetaContent(html, 'name', 'twitter:title');
  const twDescription = getMetaContent(html, 'name', 'twitter:description');
  const twImage = getMetaContent(html, 'name', 'twitter:image');
  if (!twCard || !twTitle || !twDescription || !twImage) {
    fail(`${output} missing required twitter tags (card/title/description/image)`);
  }

  const adsenseRequired = !page.validation || page.validation.adsenseRequired !== false;
  if (adsenseRequired) {
    const adsenseMeta = getMetaContent(html, 'name', 'google-adsense-account');
    if (!/^ca-pub-\d+$/.test(adsenseMeta)) {
      fail(`${output} missing valid google-adsense-account meta`);
    }
  }

  inspected += 1;
}

pass(`build output validation complete (${inspected} pages)`);
